name: Ruff
on: [push, pull_request]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v2
        with:
          src: "./"
          args: format
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "File formatted by Ruff"
